### ISSUE TITLE
request: 3mf export

### ISSUE THREAD

**Issue by diorn** [TresSims/HoudiniFileInterpreters#1]
hello, thank you for your interpreter. 
Is it possible to also have the 3mf export option?
Kind regards

**Comment by TresSims** [comment]
Hi! Sorry for not noticing this for so long. 

I'll start off by saying I'm always open to PR's if people want to contribute. 

I'm not actively working on this project right now, but if I get some free time in the future I'll see what I can do in the way of an exporter.
